# Continuous integration handling for changie
name: ci-changie

on:
  pull_request:
    paths:
      - .changes/unreleased/*.yaml
      - .changie.yaml
      - .github/workflows/ci-changie.yml

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
      - uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23 # v2.0.0
        with:
          version: latest
          args: batch patch --dry-run

